# Generated by Django 2.1.1 on 2018-12-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('date_created', models.BigIntegerField()),
                ('body', models.TextField()),
                ('last_update', models.BigIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Все новости',
            },
        ),
        migrations.CreateModel(
            name='NewsAttach',
            fields=[
                ('attach_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('url', models.TextField()),
                ('content_type', models.TextField()),
                ('date_created', models.BigIntegerField()),
                ('preview_url', models.TextField(null=True)),
                ('large_icon_url', models.TextField(null=True)),
                ('small_icon_url', models.TextField(null=True)),
                ('content_class', models.TextField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attach_news', to='news.News')),
            ],
            options={
                'verbose_name_plural': 'Все файлы',
            },
        ),
        migrations.CreateModel(
            name='NewsGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField(max_length=200)),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('date_created', models.BigIntegerField(null=True)),
                ('last_update_messages', models.BigIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Все группы',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_group', to='news.NewsGroup'),
        ),
    ]
