# Generated by Django 2.1.1 on 2018-12-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.TextField()),
                ('phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SmsVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('phone', models.TextField()),
                ('date_send', models.TextField()),
                ('device_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=1000)),
                ('expiredAt', models.TextField(max_length=500)),
                ('createdAt', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='requestauthorization',
            name='sms_verification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='authorization.SmsVerification'),
        ),
        migrations.AddField(
            model_name='auth',
            name='access_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='authorization.UserAccessToken'),
        ),
        migrations.AddField(
            model_name='auth',
            name='refresh_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to='authorization.UserAccessToken'),
        ),
    ]
