GET_ALL_GROUPS_METHOD = 'get_all_groups'
GET_ALL_NEWS_METHOD = 'get_all_news'
GET_NEWS_SELECTED_GROUPS_METHOD = 'get_news_selected_groups'
GET_NEWS_EXCEPT_GROUPS_METHOD = 'get_news_except_groups'
GET_ATTACH_METHOD = 'get_attach'
GET_IMAGE_METHOD = 'get_image'
