# Generated by Django 2.1.1 on 2018-12-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employee_positions', '0001_initial'),
        ('authorization', '0001_initial'),
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=100, verbose_name='Имя')),
                ('secondName', models.TextField(max_length=100, verbose_name='Фамилия')),
                ('thirdName', models.TextField(max_length=100, verbose_name='Отчество')),
                ('phoneNumber', models.TextField(max_length=100, verbose_name='Номер телефона')),
                ('address_residence', models.TextField(default=None, max_length=300, null=True, verbose_name='Адресс')),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
                ('employee_position', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_positions.EmployeePositions')),
                ('social_network', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='social_network.SocialNetwork')),
                ('tokens', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Auth')),
            ],
            options={
                'verbose_name_plural': 'Все сотрудники',
            },
        ),
    ]
