# Generated by Django 2.1.1 on 2018-12-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.News')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworkSite',
            fields=[
                ('name', models.CharField(choices=[('yammer', 'YAMMER'), ('vk', 'VK'), ('facebook', 'FACEBOOK')], default='yammer', max_length=30, primary_key=True, serialize=False)),
                ('token', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Все социальные сети',
            },
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='social_network_site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.SocialNetworkSite'),
        ),
    ]
